# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85401560bc3a7c504057f0d93f15e58d19b970e5523ced42f4be2f280df7167edaf46980f59d85cb74a5fb01365bedd18396adccee61c361515bfaf68ffac3ce

test:
  secret_key_base: 32e60f9674355b0beb37c32711afef09f347f47052eb3fb06085481329e78c6fa64876790d523ef319ba61d189610c0889fb80158724d11b44b57312b924e1b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
